/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubstacksIndexRouteImport } from './routes/substacks/index'
import { Route as SubstacksSlugRouteRouteImport } from './routes/substacks/$slug/route'
import { Route as SubstacksSlugIndexRouteImport } from './routes/substacks/$slug/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPortalSubstacksIndexRouteImport } from './routes/api/portal/substacks/index'
import { Route as ApiPortalSubstacksTotalRouteImport } from './routes/api/portal/substacks/total'
import { Route as ApiPortalSubstacksSlugRouteImport } from './routes/api/portal/substacks/$slug'
import { Route as ApiPortalAuthProfileRouteImport } from './routes/api/portal/auth/profile'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstacksIndexRoute = SubstacksIndexRouteImport.update({
  id: '/substacks/',
  path: '/substacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstacksSlugRouteRoute = SubstacksSlugRouteRouteImport.update({
  id: '/substacks/$slug',
  path: '/substacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SubstacksSlugIndexRoute = SubstacksSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubstacksSlugRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSubstacksIndexRoute = ApiPortalSubstacksIndexRouteImport.update({
  id: '/api/portal/substacks/',
  path: '/api/portal/substacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSubstacksTotalRoute = ApiPortalSubstacksTotalRouteImport.update({
  id: '/api/portal/substacks/total',
  path: '/api/portal/substacks/total',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalSubstacksSlugRoute = ApiPortalSubstacksSlugRouteImport.update({
  id: '/api/portal/substacks/$slug',
  path: '/api/portal/substacks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalAuthProfileRoute = ApiPortalAuthProfileRouteImport.update({
  id: '/api/portal/auth/profile',
  path: '/api/portal/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/substacks/$slug': typeof SubstacksSlugRouteRouteWithChildren
  '/substacks/': typeof SubstacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/substacks/$slug/': typeof SubstacksSlugIndexRoute
  '/api/portal/auth/profile': typeof ApiPortalAuthProfileRoute
  '/api/portal/substacks/$slug': typeof ApiPortalSubstacksSlugRoute
  '/api/portal/substacks/total': typeof ApiPortalSubstacksTotalRoute
  '/api/portal/substacks/': typeof ApiPortalSubstacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/substacks': typeof SubstacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/substacks/$slug': typeof SubstacksSlugIndexRoute
  '/api/portal/auth/profile': typeof ApiPortalAuthProfileRoute
  '/api/portal/substacks/$slug': typeof ApiPortalSubstacksSlugRoute
  '/api/portal/substacks/total': typeof ApiPortalSubstacksTotalRoute
  '/api/portal/substacks': typeof ApiPortalSubstacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/substacks/$slug': typeof SubstacksSlugRouteRouteWithChildren
  '/substacks/': typeof SubstacksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/substacks/$slug/': typeof SubstacksSlugIndexRoute
  '/api/portal/auth/profile': typeof ApiPortalAuthProfileRoute
  '/api/portal/substacks/$slug': typeof ApiPortalSubstacksSlugRoute
  '/api/portal/substacks/total': typeof ApiPortalSubstacksTotalRoute
  '/api/portal/substacks/': typeof ApiPortalSubstacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/substacks/$slug'
    | '/substacks/'
    | '/api/auth/$'
    | '/substacks/$slug/'
    | '/api/portal/auth/profile'
    | '/api/portal/substacks/$slug'
    | '/api/portal/substacks/total'
    | '/api/portal/substacks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/substacks'
    | '/api/auth/$'
    | '/substacks/$slug'
    | '/api/portal/auth/profile'
    | '/api/portal/substacks/$slug'
    | '/api/portal/substacks/total'
    | '/api/portal/substacks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/substacks/$slug'
    | '/substacks/'
    | '/api/auth/$'
    | '/substacks/$slug/'
    | '/api/portal/auth/profile'
    | '/api/portal/substacks/$slug'
    | '/api/portal/substacks/total'
    | '/api/portal/substacks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SubstacksSlugRouteRoute: typeof SubstacksSlugRouteRouteWithChildren
  SubstacksIndexRoute: typeof SubstacksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPortalAuthProfileRoute: typeof ApiPortalAuthProfileRoute
  ApiPortalSubstacksSlugRoute: typeof ApiPortalSubstacksSlugRoute
  ApiPortalSubstacksTotalRoute: typeof ApiPortalSubstacksTotalRoute
  ApiPortalSubstacksIndexRoute: typeof ApiPortalSubstacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substacks/': {
      id: '/substacks/'
      path: '/substacks'
      fullPath: '/substacks/'
      preLoaderRoute: typeof SubstacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substacks/$slug': {
      id: '/substacks/$slug'
      path: '/substacks/$slug'
      fullPath: '/substacks/$slug'
      preLoaderRoute: typeof SubstacksSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/substacks/$slug/': {
      id: '/substacks/$slug/'
      path: '/'
      fullPath: '/substacks/$slug/'
      preLoaderRoute: typeof SubstacksSlugIndexRouteImport
      parentRoute: typeof SubstacksSlugRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/substacks/': {
      id: '/api/portal/substacks/'
      path: '/api/portal/substacks'
      fullPath: '/api/portal/substacks/'
      preLoaderRoute: typeof ApiPortalSubstacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/substacks/total': {
      id: '/api/portal/substacks/total'
      path: '/api/portal/substacks/total'
      fullPath: '/api/portal/substacks/total'
      preLoaderRoute: typeof ApiPortalSubstacksTotalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/substacks/$slug': {
      id: '/api/portal/substacks/$slug'
      path: '/api/portal/substacks/$slug'
      fullPath: '/api/portal/substacks/$slug'
      preLoaderRoute: typeof ApiPortalSubstacksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/auth/profile': {
      id: '/api/portal/auth/profile'
      path: '/api/portal/auth/profile'
      fullPath: '/api/portal/auth/profile'
      preLoaderRoute: typeof ApiPortalAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SubstacksSlugRouteRouteChildren {
  SubstacksSlugIndexRoute: typeof SubstacksSlugIndexRoute
}

const SubstacksSlugRouteRouteChildren: SubstacksSlugRouteRouteChildren = {
  SubstacksSlugIndexRoute: SubstacksSlugIndexRoute,
}

const SubstacksSlugRouteRouteWithChildren =
  SubstacksSlugRouteRoute._addFileChildren(SubstacksSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SubstacksSlugRouteRoute: SubstacksSlugRouteRouteWithChildren,
  SubstacksIndexRoute: SubstacksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPortalAuthProfileRoute: ApiPortalAuthProfileRoute,
  ApiPortalSubstacksSlugRoute: ApiPortalSubstacksSlugRoute,
  ApiPortalSubstacksTotalRoute: ApiPortalSubstacksTotalRoute,
  ApiPortalSubstacksIndexRoute: ApiPortalSubstacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
