export const INVALID_CREDENTIALS_CODE = 20_000;
export const INVALID_CREDENTIALS_NAME = 'INVALID_CREDENTIALS';

export const EXPIRED_TOKEN_CODE = 20_001;
export const EXPIRED_TOKEN_NAME = 'EXPIRED_TOKEN';

export const UNAUTHORIZED_CODE = 20_002;
export const UNAUTHORIZED_NAME = 'UNAUTHORIZED';

export const CANNOT_CREATE_USER_CODE = 20_100;
export const CANNOT_CREATE_USER_NAME = 'CANNOT_CREATE_USER';

export const USER_NOT_FOUND_CODE = 20_101;
export const USER_NOT_FOUND_NAME = 'USER_NOT_FOUND';

export const USER_ALREADY_EXISTS_CODE = 20_102;
export const USER_ALREADY_EXISTS_NAME = 'USER_ALREADY_EXISTS';

export const USER_INVALID_PARAMS_CODE = 20_103;
export const USER_INVALID_PARAMS_NAME = 'USER_INVALID_PARAMS';

export const CANNOT_CREATE_TOKEN_CODE = 20_200;
export const CANNOT_CREATE_TOKEN_NAME = 'CANNOT_CREATE_TOKEN';
